// flow-typed signature: bebc6061ae4458e06d461c13f4532f48
// flow-typed version: <<STUB>>/keyboard-key_v1.0.4/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'keyboard-key'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'keyboard-key' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'keyboard-key/prettier.config' {
  declare module.exports: any;
}

declare module 'keyboard-key/src/keyboardKey' {
  declare module.exports: any;
}

declare module 'keyboard-key/test/keyboardKey.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'keyboard-key/prettier.config.js' {
  declare module.exports: $Exports<'keyboard-key/prettier.config'>;
}
declare module 'keyboard-key/src/keyboardKey.js' {
  declare module.exports: $Exports<'keyboard-key/src/keyboardKey'>;
}
declare module 'keyboard-key/test/keyboardKey.spec.js' {
  declare module.exports: $Exports<'keyboard-key/test/keyboardKey.spec'>;
}
